### ISSUE TITLE
Problem with this

### ISSUE THREAD

**Issue by skymint29** [cadnza/Chinese-Getter#1]
Hello, I'm a total newbie regarding all things code, however I've found a problem with this program(?). 

When I click "Tab", Anki pops up a window with the following error text:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-25 01:30:26

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 37, in cmd
  File "aqt\webview.py", line 123, in _onCmd
  File "aqt\webview.py", line 547, in _onBridgeCmd
  File "aqt\editor.py", line 403, in onBridgeCmd
  File "aqt\gui_hooks.py", line 1481, in __call__
  File "C:\Users\Tiago\AppData\Roaming\Anki2\addons21\972150718\__init__.py", line 205, in chineseGetter
    note.flush()
  File "anki\notes.py", line 67, in flush
AssertionError

**Comment by cadnza** [comment]
@skymint29, thanks for the feedback. This week is shaping up to be rather busy (late midterms 🤦), but I should be able to give it a look either this weekend or the next.

**Comment by skymint29** [comment]
Thank you so much!

Don't worry about it and good luck with those exams!!



A segunda, 26/10/2020, 2:33 PM, Jonathan Dayley <notifications@github.com>
escreveu:

**Comment by cadnza** [comment]
@skymint29 Sorted in [v1.0.0](). Sorry for the wait!

**Comment by skymint29** [comment]
Thank you for your attention! I hope the exams went well for you!

Best,

Tiago aka Skymint

**Comment by Splattergirl** [comment]
I was using Anki 2.1.66 and getting the same error message as above. I just tried updating to the latest version of Anki (2.4.11) to see if that would help and when I try to create a card it says something similar: "Anki encountered a problem. Please follow the troubleshooting steps. Add-ons possibly involved: Chinese Getter"

If I ignore it and just make a card anyway, using the Chinese template from Anki, it doesn't automatically add anything when I put in pinyin or a Chinese character and hit tab.

Does this add-on still work, or is there a version of Anki I can use it with?
